version: 9.5.0.{build}
environment:
    PROJECT_NAME:  'Cube.Core'
    TEST_RESULTS:  'TestResults'
    TEST_REPORT:   '%TEST_RESULTS%\Coverage'
    TEST_COVERAGE: '%TEST_RESULTS%\Coverage\Coverage.xml'
    TEST_REPORTS:  '%TEST_RESULTS%\**\coverage.cobertura.xml'

clone_folder: 'C:\Cube\%PROJECT_NAME%'
image: Visual Studio 2022
platform: Any CPU
configuration: Release
skip_tags: true
branches:
    only:
        - master
        - test_coverlet
nuget:
    project_feed: true
    disable_publish_on_pr: true
before_build:
    - nuget restore "%PROJECT_NAME%.sln"
    - nuget install ReportGenerator -Version 5.5.3
build:
    project: '%PROJECT_NAME%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      dotnet test
      --no-restore
      --no-build
      -c Release
      --settings coverlet.runsettings
      --results-directory "%TEST_RESULTS%"
      --collect:"XPlat Code Coverage"
      --logger:Appveyor
      %PROJECT_NAME%.sln


after_test:
    - >
      ".\packages\ReportGenerator.5.5.3\tools\net47\ReportGenerator.exe"
      "-reports:%TEST_REPORTS%"
      "-targetdir:%TEST_REPORT%"
      "-reporttypes:HtmlInline;Cobertura;TextSummary"    
    - choco install codecov
    - codecov -f "%TEST_COVERAGE%"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_RESULTS%\"
    - cmd: for /f "delims=" %%x in ('dir /b /s *.log') do xcopy /q /Y /I "%%x" "%TEST_RESULTS%\"
artifacts:
    - path: '%TEST_RESULTS%'
